// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.
// Regenerate: contractgen -package=hostsettings -provider-id=jev -go-package=settings -emit=go -out <path>
package settings

import (
	contract "github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/hostsettings"
	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/plugin"
)

var Validate = plugin.NewValidatedCommand[contract.ValidateRequest, contract.ValidateResult]("svc.jev.host.settings.section.v1.validate", 1, "6f32427e14f921ecf3c4221f70f6a6417d458bf3b2e3cad0a00626f5513c10d3", "svc.jev.host.settings.section.v1.validate")
