// Code generated by contractgen from SDK Go JSON contracts. DO NOT EDIT.
// Regenerate: contractgen -package=aidecision -provider-id=jev -go-package=decision -emit=go -out <path>
package decision

import (
	contract "github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/aidecision"
	"github.com/ByteDeskAI/bytedesk-sdk-dependencies/v2/plugin"
)

var Start = plugin.NewValidatedCommand[contract.ProviderStartRequest, contract.StartResult]("svc.jev.ai.decision.v1.start", 1, "8fb6576e86f4668a245b77f7da730ad663215277ac2a0366625faeaf03868716", "svc.jev.ai.decision.v1.start")
var Read = plugin.NewValidatedCommand[contract.ProviderReadRequest, contract.ReadResult]("svc.jev.ai.decision.v1.read", 1, "68563f5be3748a01643a5b87d9be6b82d64945ed2043c5e18657e9192ed0a5aa", "svc.jev.ai.decision.v1.read")
var Cancel = plugin.NewValidatedCommand[contract.ProviderCancelRequest, contract.CancelResult]("svc.jev.ai.decision.v1.cancel", 1, "76ed9a54eb8ab9da47bbe4a8af0a598faa53df93041ddf14888f4aca91aa1241", "svc.jev.ai.decision.v1.cancel")
var Models = plugin.NewValidatedCommand[contract.ProviderModelsRequest, contract.ModelsResult]("svc.jev.ai.decision.v1.models", 1, "a104edeec960635d671078733cf959cacaf1293833a3737c7ba46a5ed2a99e3d", "svc.jev.ai.decision.v1.models")
